name: REGRESSION testsuits
on:
  schedule:
    #- cron: '10 17 * * 0-6'  # Run daily at midi

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # Fixed action name

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Ensure Python version is specified

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          pip install allure-pytest

      - name: Install Java & Allure CLI
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline
          echo "ALLURE_PATH=$(npm root -g)/allure-commandline/bin" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$env:PATH;$(npm root -g)/allure-commandline/bin" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run Regression Test Suits
        run: pytest -m regression --alluredir=allure-results
        
      - name: Generate Allure Report
        run: |
          mkdir allure-report
          npx allure-commandline generate allure-results -o allure-report --clean
        continue-on-error: true


      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Scheduled Regression Tests Report"
          body: "Regression tests completed. View the Allure report here at https://dakai-wei.github.io/interview/index.html."
          to: "wei.dakai@hotmail.com"
          from: "GitHub Actions"
          attachments: allure-report/index.html
          
      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
